version: '3.7'

services:
  nginx:
    image: nginx:1.19.2-alpine
    ports:
      - "8000:8000"
      - "7000:7000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /mnt/demo:/var/www/demo

  frontend_akl:
    build:
      context: ./akll-frontend
      args:
        game: akl
    environment:
      - NODE_ENV=production

  frontend_all:
    build:
      context: ./akll-frontend
      args:
        game: all
    environment:
      - NODE_ENV=production

  backend:
    build: ./AKL-2020-Backend/
    env_file:
      - ./envs/.env.backend

  database:
    image: mongo
    restart: always
    volumes:
      - ./mongo-volume:/data/db

  challonge:
    build: ./akll-challonge/
    env_file:
      - ./envs/.env.challonge

  match_config:
    build: ./akl-match-config/
    env_file:
      - ./envs/.env.matchconfig

  match_service:
    build: ./akl-match-service/
    env_file:
      - ./envs/.env.matchservice

volumes:
  akl-volume:
  all-volume:
