version: '3.7'

services:
  nginx:
    image: nginx:1.19.2-alpine
    ports:
      - "8000:8000"
      - "7000:7000"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  frontend_akl:
    build:
      context: ./akll-frontend
      args:
        game: akl
    environment:
      - NODE_ENV=production

  frontend_all:
    build:
      context: ./akll-frontend
      args:
        game: all
    environment:
      - NODE_ENV=production

  backend:
    build: ./AKL-2020-Backend/
    env_file:
      - ./AKL-2020-Backend/.env

  database:
    image: mongo
    restart: always
    volumes:
      - ./mongo-volume:/data/db

volumes:
  akl-volume:
  all-volume:
